name: Frontend CI/CD

on:
  push:
    branches: ["master"]
    paths:
      - "session01/**"
      - ".github/workflows/front_deploy.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "session01/**"
      - ".github/workflows/front_deploy.yml"

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: CI - Build (Vite)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: session01

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: session01/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: npm run build


  cd:
    name: CD - Build/Push Docker + Deploy (VPS)
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./session01
          file: ./session01/Dockerfile
          push: true
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          tags: |
            ghcr.io/mbds-haiti/mini-projet-react-team-front:latest
            ghcr.io/mbds-haiti/mini-projet-react-team-front:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

            docker pull ghcr.io/mbds-haiti/mini-projet-react-team-front:latest

            docker stop reactteam_front || true
            docker rm reactteam_front || true

            # Publie seulement en localhost (Caddy reverse_proxy vers 5173)
            docker run -d \
              --name reactteam_front \
              --restart unless-stopped \
              -p 127.0.0.1:5173:80 \
              ghcr.io/mbds-haiti/mini-projet-react-team-front:latest
